### PR TITLE
Add docker compose playground for dashboard

### PR DESCRIPTION
**Pull request by wey-gu**
partially implement #63

For now, we make compose file build dashboard images either from the released tarball or from the current repo(for dev purposes).

In the future, we could introduce GH actions to build images and push to docker hub

### CODE REVIEW

**Comment by wey-gu** [comment]
I will test it and remove the `do not review` label then.

**Comment by wey-gu** [comment]
Now it's tested fine.

**Comment by wey-gu** [comment]
for documentation changes, just refer to the readme file, this playground is helping both testing users to play with a released version and dev users to set up a workable dashboard based on a working code base.

**Review by xigongdaEricyang — APPROVED** [review]
Thx wey-gu a lot, it looks good to me

**Pull request merged**
